name: easyflutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.4'

dependencies:
  another_flushbar: ^1.10.29
  cloud_firestore: ^3.2.1
  cupertino_icons: ^1.0.5
  data_table_2: ^2.3.5
  firebase_core: ^1.19.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  lottie: ^1.3.0
  showcaseview: ^1.1.6
  stop_watch_timer: ^1.5.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/animations/
    - assets/images/code/
    - assets/images/widget/
  uses-material-design: true
