name: easyflutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: 3.1.5
  cupertino_icons: ^1.0.2
  data_table_2: 2.2.0
  firebase_core: 1.10.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.1.0
  font_awesome_flutter: 9.2.0
  get: 4.6.1
  get_storage: 2.0.3
  google_fonts: 2.1.1
  lottie: 1.2.1
  stop_watch_timer: ^1.3.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/animations/
    - assets/images/widget/
  uses-material-design: true
