const KEY_ID_USER = "KEY_ID_USER";
const KEY_PASSWORD_USER = "KEY_PASSWORD_USER";
const KEY_NAME_USER = "KEY_NAME_USER";
const KEY_IS_LOGIN_LECTURER = "KEY_IS_LOGIN_LECTURER";
const KEY_IS_LOGIN_STUDENT = "KEY_IS_LOGIN_STUDENT";
const KEY_ID_CLASS_USER = "KEY_ID_CLASS_USER";